MODEL:
  TYPE: retinanet
  CONV_BODY: FPN.add_fpn_ResNet50_conv5_body
  NUM_CLASSES: 580 #81
NUM_GPUS: 8
SOLVER:
  WEIGHT_DECAY: 0.0001
  LR_POLICY: steps_with_decay
  BASE_LR: 0.01
  GAMMA: 0.1
  MAX_ITER: 1600000 #90000
  STEPS: [0, 1000000, 1400000]
FPN:
  FPN_ON: True
  MULTILEVEL_RPN: True
  RPN_MAX_LEVEL: 7
  RPN_MIN_LEVEL: 3
  COARSEST_STRIDE: 128
  EXTRA_CONV_LEVELS: True
RETINANET:
  RETINANET_ON: True
  NUM_CONVS: 4
  ASPECT_RATIOS: (1.0, 2.0, 0.5)
  SCALES_PER_OCTAVE: 3
  ANCHOR_SCALE: 4
  LOSS_GAMMA: 2.0
  LOSS_ALPHA: 0.25
TRAIN:
  WEIGHTS: https://dl.fbaipublicfiles.com/detectron/ImageNetPretrained/MSRA/R-50.pkl
  DATASETS: ('GOD_Open40k_train', )
  SCALES: (600,)
  MAX_SIZE: 1000
  IMS_PER_BATCH: 2
  RPN_STRADDLE_THRESH: -1  # default 0
  SNAPSHOT_ITERS: 80000 #10000
  AUTO_RESUME: True
# TEST:
#   DATASETS: ('coco_2014_minival',)
#   SCALE: 800
#   MAX_SIZE: 1333
#   NMS: 0.5
#   RPN_PRE_NMS_TOP_N: 10000  # Per FPN level
#   RPN_POST_NMS_TOP_N: 2000
OUTPUT_DIR: .
